spring:
  application:
    name: dubbo-auto-configuration-provider-demo

dubbo:
  scan:
    base-packages: com.yangbin1.user.service.impl
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A